[package]
org = "ballerina"
name = "schema_registry"
version = "@toml.version@"
authors = ["Ballerina"]
export=["schema_registry"]
keywords = ["confluent", "schema_registry", "avro", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-confluent.cregistry"
license = ["Apache-2.0"]
distribution = "2201.8.2"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/confluent.cregistry-native-0.1.0-SNAPSHOT.jar"
groupId = "io.ballerina.lib"
artifactId = "schema-registry-native"
version = "0.1.0"

[[platform.java17.dependency]]
path = "./lib/kafka-schema-registry-client-5.3.2.jar"
groupId = "io.confluent"
artifactId = "kafka-schema-registry-client"
version = "5.3.2"

[[platform.java17.dependency]]
path = "./lib/common-config-4.1.0.jar"
groupId = "io.confluent"
artifactId = "common-config"
version = "4.1.0"

[[platform.java17.dependency]]
path = "./lib/common-utils-5.3.0.jar"
groupId = "io.confluent"
artifactId = "common-utils"
version = "5.3.0"

[[platform.java17.dependency]]
path = "./lib/kafka-clients-0.11.0.1.jar"
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "0.11.0.1"

[[platform.java17.dependency]]
path = "./lib/avro-1.11.3.jar"
groupId = "org.apache.avro"
artifactId = "avro"
version = "1.11.3"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.17.0"
path = "./lib/jackson-core-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.17.0"
path = "./lib/jackson-annotations-2.17.0.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.17.0"
path = "./lib/jackson-databind-2.17.0.jar"
